### ISSUE TITLE
Missing a intro section

### ISSUE THREAD

**Issue by Anirban780** [ayush-848/Wanderblog#13]
Hey, shouldn't we create a into section just below the hero section ? Because it feels a kind of lacking where people can get a slight gist about our website and we can add a create a blog section too.

**Comment by ayush-848** [comment]
> Hey, shouldn't we create a into section just below the hero section ? Because it feels a kind of lacking where people can get a slight gist about our website and we can add a create a blog section too.

Good to go

**Comment by Anirban780** [comment]
OK , I'll work on that

**Comment by ayush-848** [comment]
> OK , I'll work on that

Have you finished it??

**Comment by Anirban780** [comment]
still working on that
